# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/nicky/Scripts/lab_analyzer/resources/ui/editor.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditorWidget(object):
    def setupUi(self, EditorWidget):
        EditorWidget.setObjectName("EditorWidget")
        EditorWidget.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(EditorWidget)
        self.verticalLayout.setObjectName("verticalLayout")

        self.retranslateUi(EditorWidget)
        QtCore.QMetaObject.connectSlotsByName(EditorWidget)

    def retranslateUi(self, EditorWidget):
        _translate = QtCore.QCoreApplication.translate
        EditorWidget.setWindowTitle(_translate("EditorWidget", "Form"))
