# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/nicky/Scripts/lab_analyzer/resources/ui/file_preview.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.toggle_frame = QtWidgets.QFrame(Form)
        self.toggle_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.toggle_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.toggle_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.toggle_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.toggle_frame.setObjectName("toggle_frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.toggle_frame)
        self.verticalLayout_5.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_5.setSpacing(2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.toggle_layout = QtWidgets.QHBoxLayout()
        self.toggle_layout.setSpacing(0)
        self.toggle_layout.setObjectName("toggle_layout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.toggle_layout.addItem(spacerItem)
        self.display_button = QtWidgets.QPushButton(self.toggle_frame)
        self.display_button.setCheckable(True)
        self.display_button.setObjectName("display_button")
        self.toggle_layout.addWidget(self.display_button)
        self.inspect_button = QtWidgets.QPushButton(self.toggle_frame)
        self.inspect_button.setCheckable(True)
        self.inspect_button.setObjectName("inspect_button")
        self.toggle_layout.addWidget(self.inspect_button)
        self.toggle_layout.setStretch(0, 2)
        self.toggle_layout.setStretch(1, 1)
        self.toggle_layout.setStretch(2, 1)
        self.verticalLayout_5.addLayout(self.toggle_layout)
        self.preview_stackedwidget = QtWidgets.QStackedWidget(self.toggle_frame)
        self.preview_stackedwidget.setMinimumSize(QtCore.QSize(100, 100))
        self.preview_stackedwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.preview_stackedwidget.setObjectName("preview_stackedwidget")
        self.plot_preview_page = QtWidgets.QWidget()
        self.plot_preview_page.setObjectName("plot_preview_page")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.plot_preview_page)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.data_preview_plot = PlotWidget(self.plot_preview_page)
        self.data_preview_plot.setMinimumSize(QtCore.QSize(0, 0))
        self.data_preview_plot.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.data_preview_plot.setObjectName("data_preview_plot")
        self.horizontalLayout_5.addWidget(self.data_preview_plot)
        self.preview_stackedwidget.addWidget(self.plot_preview_page)
        self.img_preview_page = QtWidgets.QWidget()
        self.img_preview_page.setObjectName("img_preview_page")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.img_preview_page)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.heatmap = PlotWidget(self.img_preview_page)
        self.heatmap.setObjectName("heatmap")
        self.horizontalLayout_8.addWidget(self.heatmap)
        self.preview_stackedwidget.addWidget(self.img_preview_page)
        self.inspect_page = QtWidgets.QWidget()
        self.inspect_page.setObjectName("inspect_page")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.inspect_page)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.inspect_scrollarea = QtWidgets.QScrollArea(self.inspect_page)
        self.inspect_scrollarea.setWidgetResizable(True)
        self.inspect_scrollarea.setObjectName("inspect_scrollarea")
        self.inspect_widget = QtWidgets.QWidget()
        self.inspect_widget.setGeometry(QtCore.QRect(0, 0, 356, 208))
        self.inspect_widget.setObjectName("inspect_widget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.inspect_widget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.inspect_layout = QtWidgets.QFormLayout()
        self.inspect_layout.setObjectName("inspect_layout")
        self.verticalLayout_6.addLayout(self.inspect_layout)
        self.verticalLayout_6.setStretch(0, 5)
        self.inspect_scrollarea.setWidget(self.inspect_widget)
        self.horizontalLayout_6.addWidget(self.inspect_scrollarea)
        self.preview_stackedwidget.addWidget(self.inspect_page)
        self.verticalLayout_5.addWidget(self.preview_stackedwidget)
        self.verticalLayout_5.setStretch(0, 1)
        self.verticalLayout_5.setStretch(1, 5)
        self.verticalLayout.addWidget(self.toggle_frame)

        self.retranslateUi(Form)
        self.preview_stackedwidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.display_button.setText(_translate("Form", "Display"))
        self.inspect_button.setText(_translate("Form", "Inspect"))
from pyqtgraph import PlotWidget
