# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/nicky/Scripts/lab_analyzer/resources/ui/files_dock.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_files_dockwidget(object):
    def setupUi(self, files_dockwidget):
        files_dockwidget.setObjectName("files_dockwidget")
        files_dockwidget.resize(708, 525)
        self.files_widget = QtWidgets.QWidget()
        self.files_widget.setObjectName("files_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.files_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.search_bar = QtWidgets.QLineEdit(self.files_widget)
        self.search_bar.setObjectName("search_bar")
        self.verticalLayout.addWidget(self.search_bar)
        self.tree = QtWidgets.QTreeView(self.files_widget)
        self.tree.setSortingEnabled(True)
        self.tree.setObjectName("tree")
        self.verticalLayout.addWidget(self.tree)
        files_dockwidget.setWidget(self.files_widget)

        self.retranslateUi(files_dockwidget)
        QtCore.QMetaObject.connectSlotsByName(files_dockwidget)

    def retranslateUi(self, files_dockwidget):
        _translate = QtCore.QCoreApplication.translate
        files_dockwidget.setWindowTitle(_translate("files_dockwidget", "Files"))
        self.search_bar.setPlaceholderText(_translate("files_dockwidget", "Filter files (e.g. *.hdf5)..."))
