# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/nicky/Scripts/lab_analyzer/resources/ui/hdf5_explorer.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HDF5ExplorerDock(object):
    def setupUi(self, HDF5ExplorerDock):
        HDF5ExplorerDock.setObjectName("HDF5ExplorerDock")
        HDF5ExplorerDock.resize(320, 722)
        self.hdf5_explorer_widget = QtWidgets.QWidget()
        self.hdf5_explorer_widget.setObjectName("hdf5_explorer_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.hdf5_explorer_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.file_management_layout = QtWidgets.QVBoxLayout()
        self.file_management_layout.setObjectName("file_management_layout")
        self.save_layout = QtWidgets.QHBoxLayout()
        self.save_layout.setObjectName("save_layout")
        self.save_button = QtWidgets.QPushButton(self.hdf5_explorer_widget)
        self.save_button.setObjectName("save_button")
        self.save_layout.addWidget(self.save_button)
        self.load_button = QtWidgets.QPushButton(self.hdf5_explorer_widget)
        self.load_button.setObjectName("load_button")
        self.save_layout.addWidget(self.load_button)
        self.save_layout.setStretch(0, 1)
        self.save_layout.setStretch(1, 1)
        self.file_management_layout.addLayout(self.save_layout)
        self.verticalLayout.addLayout(self.file_management_layout)
        self.explorer_layout = QtWidgets.QVBoxLayout()
        self.explorer_layout.setObjectName("explorer_layout")
        self.imported_data_tree = QtWidgets.QTreeWidget(self.hdf5_explorer_widget)
        self.imported_data_tree.setRootIsDecorated(True)
        self.imported_data_tree.setItemsExpandable(True)
        self.imported_data_tree.setObjectName("imported_data_tree")
        self.imported_data_tree.headerItem().setText(0, "File")
        self.imported_data_tree.header().setVisible(True)
        self.imported_data_tree.header().setStretchLastSection(False)
        self.explorer_layout.addWidget(self.imported_data_tree)
        self.explorer_layout.setStretch(0, 3)
        self.verticalLayout.addLayout(self.explorer_layout)
        self.verticalLayout.setStretch(1, 10)
        HDF5ExplorerDock.setWidget(self.hdf5_explorer_widget)

        self.retranslateUi(HDF5ExplorerDock)
        QtCore.QMetaObject.connectSlotsByName(HDF5ExplorerDock)

    def retranslateUi(self, HDF5ExplorerDock):
        _translate = QtCore.QCoreApplication.translate
        HDF5ExplorerDock.setWindowTitle(_translate("HDF5ExplorerDock", "HDF5 Explorer"))
        self.save_button.setText(_translate("HDF5ExplorerDock", "Save"))
        self.load_button.setText(_translate("HDF5ExplorerDock", "Load"))
        self.imported_data_tree.headerItem().setText(1, _translate("HDF5ExplorerDock", "Kind"))
