# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/nicky/Scripts/lab_analyzer/resources/ui/log_registry.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LogRegistryDock(object):
    def setupUi(self, LogRegistryDock):
        LogRegistryDock.setObjectName("LogRegistryDock")
        LogRegistryDock.resize(840, 305)
        self.log_registry_widget = QtWidgets.QWidget()
        self.log_registry_widget.setObjectName("log_registry_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.log_registry_widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.log_view = QtWidgets.QTableView(self.log_registry_widget)
        self.log_view.setObjectName("log_view")
        self.horizontalLayout.addWidget(self.log_view)
        self.filter_tree = QtWidgets.QTreeWidget(self.log_registry_widget)
        self.filter_tree.setObjectName("filter_tree")
        item_0 = QtWidgets.QTreeWidgetItem(self.filter_tree)
        item_0.setCheckState(0, QtCore.Qt.Checked)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Checked)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Checked)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Checked)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Checked)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Checked)
        self.filter_tree.header().setVisible(True)
        self.horizontalLayout.addWidget(self.filter_tree)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 1)
        LogRegistryDock.setWidget(self.log_registry_widget)

        self.retranslateUi(LogRegistryDock)
        QtCore.QMetaObject.connectSlotsByName(LogRegistryDock)

    def retranslateUi(self, LogRegistryDock):
        _translate = QtCore.QCoreApplication.translate
        LogRegistryDock.setWindowTitle(_translate("LogRegistryDock", "Log"))
        self.filter_tree.headerItem().setText(0, _translate("LogRegistryDock", "Display:"))
        __sortingEnabled = self.filter_tree.isSortingEnabled()
        self.filter_tree.setSortingEnabled(False)
        self.filter_tree.topLevelItem(0).setText(0, _translate("LogRegistryDock", "All message types"))
        self.filter_tree.topLevelItem(0).child(0).setText(0, _translate("LogRegistryDock", "info"))
        self.filter_tree.topLevelItem(0).child(1).setText(0, _translate("LogRegistryDock", "warning"))
        self.filter_tree.topLevelItem(0).child(2).setText(0, _translate("LogRegistryDock", "error"))
        self.filter_tree.topLevelItem(0).child(3).setText(0, _translate("LogRegistryDock", "critical"))
        self.filter_tree.topLevelItem(0).child(4).setText(0, _translate("LogRegistryDock", "debug"))
        self.filter_tree.setSortingEnabled(__sortingEnabled)
