# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/nicky/Scripts/lab_analyzer/resources/ui/plot_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_plot_window(object):
    def setupUi(self, plot_window):
        plot_window.setObjectName("plot_window")
        plot_window.resize(539, 486)
        self.plot_widget = QtWidgets.QWidget(plot_window)
        self.plot_widget.setObjectName("plot_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.plot_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mpl_plot_layout = QtWidgets.QVBoxLayout()
        self.mpl_plot_layout.setObjectName("mpl_plot_layout")
        self.verticalLayout.addLayout(self.mpl_plot_layout)
        self.residuals_layout = QtWidgets.QVBoxLayout()
        self.residuals_layout.setObjectName("residuals_layout")
        self.verticalLayout.addLayout(self.residuals_layout)
        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(1, 1)
        plot_window.setCentralWidget(self.plot_widget)
        self.plot_menubar = QtWidgets.QMenuBar(plot_window)
        self.plot_menubar.setGeometry(QtCore.QRect(0, 0, 539, 39))
        self.plot_menubar.setObjectName("plot_menubar")
        plot_window.setMenuBar(self.plot_menubar)
        self.plot_statusbat = QtWidgets.QStatusBar(plot_window)
        self.plot_statusbat.setObjectName("plot_statusbat")
        plot_window.setStatusBar(self.plot_statusbat)

        self.retranslateUi(plot_window)
        QtCore.QMetaObject.connectSlotsByName(plot_window)

    def retranslateUi(self, plot_window):
        _translate = QtCore.QCoreApplication.translate
        plot_window.setWindowTitle(_translate("plot_window", "Plot"))
