# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/nicky/Scripts/lab_analyzer/resources/ui/untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_plot_widget(object):
    def setupUi(self, plot_widget):
        plot_widget.setObjectName("plot_widget")
        plot_widget.resize(639, 624)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(plot_widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.mpl_plot_layout = QtWidgets.QVBoxLayout()
        self.mpl_plot_layout.setObjectName("mpl_plot_layout")
        self.verticalLayout_2.addLayout(self.mpl_plot_layout)

        self.retranslateUi(plot_widget)
        QtCore.QMetaObject.connectSlotsByName(plot_widget)

    def retranslateUi(self, plot_widget):
        _translate = QtCore.QCoreApplication.translate
        plot_widget.setWindowTitle(_translate("plot_widget", "Form"))
