# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/nicky/Scripts/lab_analyzer/resources/ui/workspace_dockwidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_workspace_dockwidget(object):
    def setupUi(self, workspace_dockwidget):
        workspace_dockwidget.setObjectName("workspace_dockwidget")
        workspace_dockwidget.resize(425, 207)
        self.workspace_widget = QtWidgets.QWidget()
        self.workspace_widget.setObjectName("workspace_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.workspace_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.workspace_table = QtWidgets.QTableWidget(self.workspace_widget)
        self.workspace_table.setObjectName("workspace_table")
        self.workspace_table.setColumnCount(2)
        self.workspace_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.workspace_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.workspace_table.setHorizontalHeaderItem(1, item)
        self.verticalLayout.addWidget(self.workspace_table)
        workspace_dockwidget.setWidget(self.workspace_widget)

        self.retranslateUi(workspace_dockwidget)
        QtCore.QMetaObject.connectSlotsByName(workspace_dockwidget)

    def retranslateUi(self, workspace_dockwidget):
        _translate = QtCore.QCoreApplication.translate
        workspace_dockwidget.setWindowTitle(_translate("workspace_dockwidget", "Workspace"))
        item = self.workspace_table.horizontalHeaderItem(0)
        item.setText(_translate("workspace_dockwidget", "Name"))
        item = self.workspace_table.horizontalHeaderItem(1)
        item.setText(_translate("workspace_dockwidget", "Value"))
